---
- hosts: main

  tasks:
  - name: run alertmanager container
    community.docker.docker_container:
      name: alertmanager
      image: prom/alertmanager
      ports:
        - 9093:9093
      volumes:
        - ./alertmanager:/etc/alertmanager
      command:
        - --config.file=/etc/alertmanager/config.yml
        - --storage.path=/alertmanager

  # - name: run cadvisor container
  #   community.docker.docker_container:
  #     name: cadvisor
  #     image: google/cadvisor
  #     volumes:
  #       - /:/rootfs:ro
  #       - /var/run:/var/run:rw
  #       - /sys:/sys:ro
  #       - /var/lib/docker/:/var/lib/docker:ro
  #     ports:
  #       - 8080:8080

  # - name: run prometheus container
  #   community.docker.docker_container:
  #     name: prometheus
  #     image: prom/prometheus:latest
  #     volumes:
  #       - ./prometheus/:/etc/prometheus/
  #       - prometheus_data:/prometheus
  #     command:
  #       - '--config.file=/etc/prometheus/prometheus.yml'
  #       - '--storage.tsdb.path=/prometheus'
  #       - '--web.console.libraries=/usr/share/prometheus/console_libraries'
  #       - '--web.console.templates=/usr/share/prometheus/consoles'
  #     ports: 9090:9090
  #     links:
  #       - "cadvisor:cadvisor"
  #       - "alertmanager:alertmanager"

  # - name: run grafana container
  #   community.docker.docker_container:
  #     name: grafana
  #     image: grafana/grafana
  #     user: "472"
  #     depends_on:
  #       - prometheus
  #     ports:
  #       - 3000:3000
  #     volumes:
  #       - grafana_data:/var/lib/grafana
  #       - ./grafana/provisioning/:/etc/grafana/provisioning/
  #     env_file:
  #       - ./grafana/config.monitoring